name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        cache: 'maven'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
    - name: Build with Maven
      run: mvn clean package -DSHA=${{ steps.vars.outputs.sha_short }} -Dbuild.type=github -Dbuild.number=${{ github.run_number }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: BungeeCord Artifacts
        path: bootstrap/target/BungeeCord.jar
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Module Artifacts
        path: "module/**/target/*.jar"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "v${{ github.run_number }}"
        draft: false
        prerelease: false
    - name: Upload Release Asset - BungeeCord.jar
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bootstrap/target/BungeeCord.jar
        asset_name: BungeeCord.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_alert.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-alert/target/cmd_alert.jar
        asset_name: cmd_alert.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_bungee.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-bungee/target/cmd_bungee.jar
        asset_name: cmd_bungee.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_find.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-find/target/cmd_find.jar
        asset_name: cmd_find.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_kick.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-kick/target/cmd_kick.jar
        asset_name: cmd_kick.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_list.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-list/target/cmd_list.jar
        asset_name: cmd_list.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_send.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-send/target/cmd_send.jar
        asset_name: cmd_send.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_server.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-server/target/cmd_server.jar
        asset_name: cmd_server.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/reconnect_yaml.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/reconnect-yaml/target/reconnect_yaml.jar
        asset_name: reconnect_yaml.jar
        asset_content_type: application/java-archive
    - name: Check Hash
      id: md5
      run: |
        set -x
        export BOOTSTRAP=$(md5sum ./bootstrap/target/BungeeCord.jar | cut -d ' ' -f 1)
        export MODULES_ALERT=$(md5sum ./module/cmd-alert/target/cmd_alert.jar | cut -d ' ' -f 1)
        export MODULES_BUNGEE=$(md5sum ./module/cmd-bungee/target/cmd_bungee.jar | cut -d ' ' -f 1)
        export MODULES_FIND=$(md5sum ./module/cmd-find/target/cmd_find.jar | cut -d ' ' -f 1)
        export MODULES_KICK=$(md5sum ./module/cmd-kick/target/cmd_kick.jar | cut -d ' ' -f 1)
        export MODULES_LIST=$(md5sum ./module/cmd-list/target/cmd_list.jar | cut -d ' ' -f 1)
        export MODULES_SEND=$(md5sum ./module/cmd-send/target/cmd_send.jar | cut -d ' ' -f 1)
        export MODULES_SERVER=$(md5sum ./module/cmd-server/target/cmd_server.jar | cut -d ' ' -f 1)
        export MODULES_RECONNECT=$(md5sum ./module/reconnect-yaml/target/reconnect_yaml.jar | cut -d ' ' -f 1)
        echo ::set-output name=bootstrap::"$BOOTSTRAP"
        echo ::set-output name=modules_alert::"$MODULES_ALERT"
        echo ::set-output name=modules_bungee::"$MODULES_BUNGEE"
        echo ::set-output name=modules_find::"$MODULES_FIND"
        echo ::set-output name=modules_kick::"$MODULES_KICK"
        echo ::set-output name=modules_list::"$MODULES_LIST"
        echo ::set-output name=modules_send::"$MODULES_SEND"
        echo ::set-output name=modules_server::"$MODULES_SERVER"
        echo ::set-output name=modules_reconnect::"$MODULES_RECONNECT"
        set +x
    - name: Update Release
      uses: irongut/EditRelease@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        id: ${{ steps.create_release.outputs.id }}
        body: |
          | Filename  | MD5 Hash |
          | ------------- | ------------- |
          | [BungeeCord.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/BungeeCord.jar)  | ${{ steps.md5.outputs.bootstrap }} |
          | [cmd_alert.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/cmd_alert.jar)  | ${{ steps.md5.outputs.modules_alert }} |
          | [cmd_bungee.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/cmd_bungee.jar)  | ${{ steps.md5.outputs.modules_bungee }} |
          | [cmd_find.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/cmd_find.jar)  | ${{ steps.md5.outputs.modules_find }} |
          | [cmd_kick.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/cmd_kick.jar)  | ${{ steps.md5.outputs.modules_kick }} |
          | [cmd_list.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/cmd_list.jar)  | ${{ steps.md5.outputs.modules_list }} |
          | [cmd_send.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/cmd_send.jar)  | ${{ steps.md5.outputs.modules_send }} |
          | [cmd_server.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/cmd_server.jar)  | ${{ steps.md5.outputs.modules_server }} |
          | [reconnect_yaml.jar](https://github.com/SimplyRin/BungeeCord/releases/download/v${{ github.run_number }}/reconnect_yaml.jar)  | ${{ steps.md5.outputs.modules_reconnect }} |
