name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
        cache: 'maven'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
    - name: Build with Maven
      run: mvn clean package -DSHA=${{ steps.vars.outputs.sha_short }} -Dbuild.type=github -Dbuild.number=${{ github.run_number }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: BungeeCord Artifacts
        path: bootstrap/target/BungeeCord.jar
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Module Artifacts
        path: "module/**/target/*.jar"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "v${{ github.run_number }}"
        draft: false
        prerelease: false
    - name: Upload Release Asset - BungeeCord.jar
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bootstrap/target/BungeeCord.jar
        asset_name: BungeeCord.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_alert.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-alert/target/cmd_alert.jar
        asset_name: cmd_alert.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_bungee.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-bungee/target/cmd_bungee.jar
        asset_name: cmd_bungee.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_find.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-find/target/cmd_find.jar
        asset_name: cmd_find.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_kick.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-kick/target/cmd_kick.jar
        asset_name: cmd_kick.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_list.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-list/target/cmd_list.jar
        asset_name: cmd_list.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_send.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-send/target/cmd_send.jar
        asset_name: cmd_send.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/cmd_server.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/cmd-server/target/cmd_server.jar
        asset_name: cmd_server.jar
        asset_content_type: application/java-archive
    - name: Upload Release Asset - module/reconnect_yaml.jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./module/reconnect-yaml/target/reconnect_yaml.jar
        asset_name: reconnect_yaml.jar
        asset_content_type: application/java-archive
